# Generated by Django 4.1.1 on 2022-09-20 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Platform X', max_length=150)),
                ('key', models.CharField(max_length=150, null=True, unique=True)),
                ('icon', models.ImageField(blank=True, default='platform/social-media.png', null=True, upload_to='platform/')),
                ('is_active', models.BooleanField(default=True)),
                ('minimum_allowed_users', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dra_tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='extras_platform_detail',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_completed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_medium',
            field=models.CharField(blank=True, choices=[('web', 'Website'), ('app', 'App')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CorporateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation_name', models.CharField(blank=True, max_length=250, null=True)),
                ('nature_of_business', models.CharField(blank=True, max_length=250, null=True)),
                ('website_link', models.CharField(blank=True, max_length=250, null=True)),
                ('company_address', models.TextField(blank=True, max_length=500, null=True)),
                ('company_pancard_number', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_of_incorporation', models.FileField(blank=True, null=True, upload_to='corporate/')),
                ('moa', models.FileField(blank=True, null=True, upload_to='corporate/')),
                ('aoa', models.FileField(blank=True, null=True, upload_to='corporate/')),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='corporate/')),
                ('cancelled_cheque', models.FileField(blank=True, null=True, upload_to='corporate/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pan_no', models.CharField(max_length=100, null=True)),
                ('pan_card_file', models.FileField(blank=True, null=True, upload_to='bank_detail')),
                ('bank_account_no', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=150, null=True)),
                ('account_holder_name', models.CharField(max_length=200, null=True)),
                ('ifsc_code', models.CharField(max_length=100, null=True)),
                ('cancelled_cheque', models.FileField(blank=True, null=True, upload_to='bank_detail')),
                ('aadhar_card_file', models.FileField(blank=True, null=True, upload_to='bank_detail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.platform'),
        ),
        migrations.CreateModel(
            name='MobileVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'code')},
            },
        ),
    ]
