# Generated by Django 4.1.1 on 2022-09-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_platform_user_aadhar_number_user_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_name',
            new_name='account_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
