# Generated by Django 4.0 on 2022-10-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_activated_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_aggre_term_condition',
            field=models.BooleanField(default=False),
        ),
    ]
