# Generated by Django 4.0 on 2022-10-03 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_brokerage_percentage_user_incentive_perlead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('unapproved', 'UnApproved'), ('approved', 'Approved')], default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mx_referred_dra_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='term_condition_content',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
