# Generated by Django 4.0 on 2022-10-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_kyc',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
