# Generated by Django 4.0 on 2022-10-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_term_condition_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_brokerage',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=14, null=True),
        ),
    ]
