# Generated by Django 4.0 on 2022-10-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_total_brokerage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'rm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user'),
        ),
    ]
