# Generated by Django 4.0 on 2022-10-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_is_activated_alter_user_reporting_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dra_code_encrypted',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
