# Generated by Django 4.0 on 2022-10-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_dra_code_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dra_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
