# Generated by Django 4.0 on 2022-10-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_kyc',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
