# Generated by Django 4.0 on 2022-12-02 13:04

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_user_term_condition_agree_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='bankdetail',
            options={'verbose_name': 'Bank Detail', 'verbose_name_plural': 'Bank Detail'},
        ),
        migrations.AlterModelOptions(
            name='corporatedetail',
            options={'verbose_name': 'Corporate Detail', 'verbose_name_plural': 'Corporate Detail'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Level', 'verbose_name_plural': 'Level'},
        ),
        migrations.AlterModelOptions(
            name='mobileverificationcode',
            options={'verbose_name': 'Mobile Verification Code', 'verbose_name_plural': 'Mobile Verification Code'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Platform', 'verbose_name_plural': 'Platforms'},
        ),
        migrations.AlterModelOptions(
            name='timingslot',
            options={'verbose_name': 'Timing Slot', 'verbose_name_plural': 'Timing Slot'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AddField(
            model_name='user',
            name='previous_brokerage_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(30.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='previous_incentive_perlead',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='term_condition_content',
            field=tinymce.models.HTMLField(blank=True, max_length=2500, null=True, verbose_name='Remark'),
        ),
    ]
