# Generated by Django 4.0 on 2023-02-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_level_bg_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='term_condition_content',
            new_name='remark',
        ),
    ]
