# Generated by Django 4.0 on 2023-03-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'dsa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('dsa', 'DSA'), ('rmj', 'RMJ')], default='rmj', max_length=100, null=True),
        ),
    ]
