# Generated by Django 4.0 on 2023-04-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_user_reporting_manager_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dra_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='user tag'),
        ),
    ]
