# Generated by Django 4.0 on 2022-09-28 10:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'tags',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='KnowlageCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='knowlage-center-image/')),
                ('content', tinymce.models.HTMLField(blank=True, max_length=4096, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='core.Tags')),
            ],
            options={
                'verbose_name': 'Knowlage Center',
                'verbose_name_plural': 'Knowlage Center',
            },
        ),
        migrations.CreateModel(
            name='KnowlageAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='knowlage-assets/')),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('knowlage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.knowlagecenter')),
            ],
            options={
                'verbose_name': 'Knowlage Assets',
                'verbose_name_plural': 'Knowlage Assets',
            },
        ),
    ]
