# Generated by Django 4.0 on 2022-09-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_tags_knowlagecenter_knowlageassets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowlagecenter',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tags'),
        ),
    ]
