# Generated by Django 4.0 on 2022-10-01 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
