# Generated by Django 4.0 on 2022-10-03 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_brokerage_percentage_user_incentive_perlead_and_more'),
        ('core', '0006_brokerage_level_payout_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incentive_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('dra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('prospect_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mx_client_code', models.CharField(blank=True, max_length=100, null=True)),
                ('mx_dra_code', models.CharField(blank=True, max_length=100, null=True)),
                ('mx_referred_dra_code', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('source_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('source_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('mx_diy_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('lsq_created_on', models.DateTimeField(blank=True, null=True)),
                ('my_first_trade_date', models.DateTimeField(blank=True, null=True)),
                ('dra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='payout',
            old_name='date',
            new_name='voucher_date',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='mx_dra_code',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='brokerage',
            name='api_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerage',
            name='dra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AddField(
            model_name='brokerage',
            name='dra_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brokerage',
            name='sharing',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='brokerage',
            name='total_cummulative_brokerage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='brokerage',
            name='total_cumulative_net_brokerage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='brokerage',
            name='unique_cummulative_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='ac_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='clear_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='particulars',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='vtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='dra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.AddField(
            model_name='incentive',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leads'),
        ),
    ]
