# Generated by Django 4.0 on 2022-10-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowlagecenter',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
