# Generated by Django 4.0 on 2022-10-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='trad_active',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
