# Generated by Django 4.0 on 2022-10-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_settlement_trad_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='converted',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
