# Generated by Django 4.0 on 2022-10-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_total_kyc'),
        ('core', '0012_alter_settlement_converted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'keywords',
                'verbose_name_plural': 'keywords',
            },
        ),
        migrations.AlterField(
            model_name='leads',
            name='dra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_leads', to='account.user'),
        ),
        migrations.AlterUniqueTogether(
            name='incentive',
            unique_together={('dra', 'lead')},
        ),
    ]
