# Generated by Django 4.0 on 2022-10-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_keyword_alter_leads_dra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='app_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
