# Generated by Django 4.0 on 2022-10-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_financialyear_tdscertificate_tds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerage',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
