# Generated by Django 4.0 on 2022-11-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_brokerage_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdscertificate',
            name='tds_certificate',
            field=models.FileField(blank=True, null=True, upload_to='tds-certificate/'),
        ),
        migrations.AlterField(
            model_name='overviewbanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Image dimension should be (1920 x 200)', null=True, upload_to='dashboard/banner/'),
        ),
    ]
