# Generated by Django 4.0 on 2022-12-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_tdscertificate_quarter_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokerage',
            options={'verbose_name': 'Brokerage', 'verbose_name_plural': 'Brokerage'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='financialyear',
            options={'verbose_name': 'Financial Year', 'verbose_name_plural': 'Financial Year'},
        ),
        migrations.AlterModelOptions(
            name='incentive',
            options={'verbose_name': 'Incentive', 'verbose_name_plural': 'Incentive'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='knowlageassets',
            options={'verbose_name': 'Knowledge Assets', 'verbose_name_plural': 'Knowledge Assets'},
        ),
        migrations.AlterModelOptions(
            name='knowlagecenter',
            options={'verbose_name': 'Knowledge Center', 'verbose_name_plural': 'Knowledge Center'},
        ),
        migrations.AlterModelOptions(
            name='leads',
            options={'verbose_name': 'Leads', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='overviewbanner',
            options={'verbose_name': 'Overview Banner', 'verbose_name_plural': 'Overview Banner'},
        ),
        migrations.AlterModelOptions(
            name='payout',
            options={'verbose_name': 'Payout', 'verbose_name_plural': 'Payout'},
        ),
        migrations.AlterModelOptions(
            name='segment',
            options={'verbose_name': 'Segment', 'verbose_name_plural': 'Segment'},
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={'verbose_name': 'Settlement', 'verbose_name_plural': 'Settlement'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tdscertificate',
            options={'verbose_name': 'TDS Certificate', 'verbose_name_plural': 'TDS Certificate'},
        ),
    ]
