# Generated by Django 4.0 on 2023-01-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_knowlageassets_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdscertificate',
            name='segment',
        ),
    ]
