# Generated by Django 4.0 on 2023-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_leads_mandate_status_leads_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Payment Done', 'Payment Done'), ('On Hold', 'On Hold')], max_length=100, null=True),
        ),
    ]
