# Generated by Django 4.0 on 2023-03-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_user_user_type'),
        ('core', '0026_payout_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='dra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_leads', to='account.user'),
        ),
    ]
