# Generated by Django 4.0 on 2023-03-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_leads_dra'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
