# Generated by Django 4.0 on 2023-03-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_payout_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='rm_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
