# Generated by Django 4.0 on 2023-04-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_payout_rm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='mandate_status',
            field=models.CharField(blank=True, choices=[('Not Initiated', 'Not Initiated'), ('In-Process', 'In-Process'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default='Not Initiated', max_length=100, null=True),
        ),
    ]
