# Generated by Django 4.0 on 2023-04-11 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowlagecenter',
            name='image',
            field=models.ImageField(blank=True, help_text='Image should be in 1920*1080px dimension', null=True, upload_to='knowlage-center-image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
